version: "3"

services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybdtest
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306

    depends_on:
    - db






